toybox/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from views.borrow import borrow
from views.members import members
from views.returns import returns
from views.transactions import transactions
from views.toys import toys
from views.feedback import feedback
from views.shifts import shifts



urlpatterns = [
                  url(r'^$', shifts, name='home'),
                  url(r'^borrow/$', borrow, kwargs=dict(member_id=None), name='borrow'),
                  url(r'^borrow/(?P<member_id>[0-9]+)/$', borrow, name='borrow'),
                  # url(r'^borrow/success/$', borrow, kwargs=dict(member_id=None), name='borrow'),
                  url(r'^returns/$', returns, name='returns'),
                  url(r'^returns/(?P<member_id>[0-9]+)/$',  returns, name='returns'),
                  url(r'^members/$', members, name='members'),
                  url(r'^members/(?P<member_id>[0-9]+)/$', members, name='members'),
                  url(r'^shifts/', shifts, name='shifts'),
                  url(r'^transactions/', transactions, name='transactions'),
                  url(r'^toys/$',toys, name='toys'),
                  url(r'^toys/(?P<toy_id>\w{0,50})/$',toys, name='toys'),
                  url(r'^feedback/', feedback, name='feedback'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

treasurechest/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse

urlpatterns = [
    url(r'^login/', auth_views.login,{'extra_context':{'title': 'Login'}}),
    url(r'^logout/$', auth_views.logout_then_login),
    url(r'^$', views.base, name='base'),
    url(r'^toybox/', include('toybox.urls', namespace="toybox")),
    url(r'^admin/', include(admin.site.urls)),
    url('^', include('django.contrib.auth.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toybox/models.py
import datetime
import django
from datetime import date
from datetime import timedelta
from decimal import *

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import Permission, User
import os.path



def thisDateTime():
    return timezone.make_aware(datetime.datetime.now(),timezone.get_default_timezone())

def format_username(user):

    if user.first_name=="":
        result= user.username
    else:
        result=user.first_name+" "+user.last_name
    return result


class Config(models.Model):

    STRING =0
    NUMBER=1
    BOOLEAN=2

    CONFIG_TYPES = (
        (STRING,"String"),
        (NUMBER,"Number"),
        (BOOLEAN,"Boolean"),
    )


    key = models.CharField(max_length=30, unique=True)
    value = models.CharField(max_length=100)
    value_type =  models.IntegerField(default=STRING, choices=CONFIG_TYPES)
    help = models.CharField(max_length=1024, default="")

    def __unicode__(self):
        return self.key + " = " + self.value + "  (" + self.help + ")"

    def __str__(self):
        return self.key + " = " + self.value + "  (" + self.help + ")"


class MemberType(models.Model):
    YEARLY = 365
    BIANNUALLY = 183
    # QUARTERLY = 13


    MEMBER_PERIOD_CHOICES = (
        (YEARLY, 'Yearly'),
        (BIANNUALLY, 'Biannually'),
        # (QUARTERLY, 'Quarterly'),
    )
    membership_period = models.IntegerField(default=YEARLY, choices=MEMBER_PERIOD_CHOICES)
    name = models.CharField(max_length=20)
    fee = models.DecimalField(decimal_places=2, max_digits=5,default=0)
    bond = models.DecimalField(decimal_places=2, max_digits=5, default=0)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


class ToyCategory(models.Model):
    name = models.CharField(max_length=50)
    code_prefix = models.CharField(max_length=2)
    next_code_number = models.PositiveSmallIntegerField(default=0)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

class RecycledToyId(models.Model):
    toy_id = models.CharField(max_length=6)
    category = models.ForeignKey(ToyCategory)

    def __unicode__(self):
        return self.id

    def __str__(self):
        return self.id

class Member(models.Model):

    # surname?
    name = models.CharField(max_length=100)
    partner = models.CharField(max_length=100, blank=True)
    address = models.CharField(max_length=300)
    phone_number1 = models.CharField(max_length=12)
    phone_number2 = models.CharField(max_length=12, blank=True)
    email_address = models.EmailField()
    volunteer = models.BooleanField('Active volunteer', default=False)
    potential_volunteer = models.BooleanField(default=False)
    committee_member = models.BooleanField('Current committee member', default=False)
    membership_end_date = models.DateField('Membership due', default=date.today, blank=True)
    balance = models.DecimalField('Balance', decimal_places=2, max_digits=6, default=0)
    active = models.BooleanField(default=True)
    type = models.ForeignKey(MemberType)
    join_date = models.DateField(auto_now_add=True, blank=True)
    bond_fee_paid = models.DecimalField(decimal_places=2, max_digits=5, default=0)
    bond_refunded = models.DateField('Deposit refunded', null=True, blank=True)
    bond_absorbed = models.DateField('Deposit absorbed', null=True, blank=True)
    volunteer_capacity_wed = models.BooleanField(default=False)
    volunteer_capacity_sat = models.BooleanField(default=False)
    comment = models.CharField(max_length=1024, blank=True)
    bond_receipt_reference = models.CharField(max_length=64, default=None, null=True)
    #TODO
    # roster days - bitfield
    # member notes/characteristics?


    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

    # def membership_due_soon(self):
    #     # TODO move magic value to config
    #     return datetime.datetime.now().date + datetime.timedelta(days=60) <= self.membership_end_date

    def membership_valid(self):
        return (thisDateTime().now().date() < self.membership_end_date) or (self.type.fee==0)


    def bond_paid(self):
         return self.bond_fee_paid >0

    def is_current(self):
        return  self.membership_valid() and self.bond_paid()

    def update_membership_date(self):
        self.membership_end_date = thisDateTime().now().date()+timedelta(days=self.type.membership_period)
        self.save()


    def membership_warning(self):
        from views.shared import get_config
        warning_duration = get_config("membership_warning_duration")
        days_until_membershiup_due = (self.membership_end_date - thisDateTime().now().date()).days
        membership_soon = days_until_membershiup_due > 0 and days_until_membershiup_due <= warning_duration
        return membership_soon

    def status(self):
        if self.is_current():
            if self.member_warning():
               return "Upcoming"
            else:
                return "Valid"
        else:
            return "Due"



class Child(models.Model):

    date_of_birth = models.DateField()
    parent = models.ForeignKey(Member)

    def __unicode__(self):
        return str(self.date_of_birth)

    def __str__(self):
        return str(self.date_of_birth)


class ToyBrand(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


class ToyPackaging(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

class ToyVendor(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name







def image_file_name(self, filename):
    return Image.image_path(filename, self.type)

class Image(models.Model):

    TOY = 0
    RECEIPT = 1
    INSTRUCTIONS = 2

    IMAGE_TYPE_CHOICES = (
        (TOY, "Toy"),
        (RECEIPT, "Receipt"),
        (INSTRUCTIONS, "Instructions")
    )
    # Separate images into subdirectories based on type
    @staticmethod
    def image_path (filename, type):
        dir = {
            Image.TOY: 'toys',
            Image.RECEIPT: 'receipts',
            Image.INSTRUCTIONS: 'instructions'
        }
        type_dir = dir[type]
        file_path = os.path.join("images", type_dir, filename)
        return file_path

    file = models.ImageField(upload_to=image_file_name)  # need Pillow (pip install Pillow)
    type = models.IntegerField(choices=IMAGE_TYPE_CHOICES)
    primary = models.BooleanField(default=False)

    def __unicode__(self):
        return unicode(self.file.name+" ["+self.IMAGE_TYPE_CHOICES[self.type][1]+"]")

    def __str__(self):
        return unicode(self.file.name+" ["+self.IMAGE_TYPE_CHOICES[self.type][1]+"]")

    def admin_image(self):
        if self.file != None:
            return u'<img src="%s" style="max-height:150px;image-orientation:from-image;" />' % self.file.url
        else:
            return "NO IMAGE"

    admin_image.allow_tags = True

class Toy(models.Model):
    AVAILABLE = 0
    ON_LOAN = 1
    STOCKTAKE = 2
    TO_BE_REPAIRED = 3
    BEING_REPAIRED = 4
    RETIRED = 5
    TO_BE_RETIRED = 6
    MISSING = 7
    TO_BE_CATALOGED = 8

    TOY_STATE_CHOICES = (
        (AVAILABLE, 'Available'),
        (ON_LOAN, 'On Loan'),
        (STOCKTAKE, 'Stocktake'),
        (TO_BE_REPAIRED, 'To Be Repaired'),
        (BEING_REPAIRED, 'Being Repaired'),
        (RETIRED, 'Retired'),
        (TO_BE_RETIRED, 'To Be Assessed'),
        (MISSING, 'Missing'),
        (TO_BE_CATALOGED, 'To Be Cataloged'),
    )

    ISSUE_NONE = 0
    BROKEN_REPAIRABLE = 1
    BROKEN_NOT_REPAIRABLE = 2
    MINOR_MISSING_PIECE = 3
    MAJOR_MISSING_PIECE = 4
    WHOLE_TOY_MISSING = 5
    #RETIRE_VERIFIED =6
    # not an issue, how would these been entered? - Not a "return" but noted in toy history?
    # RETURNED_MISSING_PIECE = 6
    # RETURNED_MISSING_TOY = 7





    ISSUE_TYPE_CHOICES = (
        (ISSUE_NONE, 'No Issue'),
        (BROKEN_REPAIRABLE, 'Broken repairable'),  # -> to admin cupboard
        (BROKEN_NOT_REPAIRABLE, 'Broken not repairable'),  # -> to be retired
        (MINOR_MISSING_PIECE, 'Minor missing piece'),  # -> to shelf
        (MAJOR_MISSING_PIECE, 'Major missing piece'),  # -> to admin cupboard
        (WHOLE_TOY_MISSING, 'Whole toy missing'),  # -> to be retired
        #(RETIRE_VERIFIED, 'Verified to retire'),
        # who can retire a toy?
        # (RETURNED_MISSING_PIECE, 'Returned missing piece'),
        # (RETURNED_MISSING_TOY, 'Returned missing toy'),

    )

    #percentage of toy cost
    # ISSUE_FINE_MAJOR_MIN=Decimal(0.1)
    # ISSUE_FINE_MAJOR_MAX=Decimal(0.5)
    # ISSUE_FINE_MINOR_MIN=Decimal(0.1)
    # ISSUE_FINE_MINOR_MAX=Decimal(0.3)

    ISSUE_FINE_NONE =0
    ISSUE_FINE_MINOR =1
    ISSUE_FINE_MAJOR =2



    ISSUE_FINE_CHOICES = (
        (ISSUE_NONE, ISSUE_FINE_NONE),
        (BROKEN_REPAIRABLE, ISSUE_FINE_MINOR),
        (BROKEN_NOT_REPAIRABLE,ISSUE_FINE_MAJOR),
        (MINOR_MISSING_PIECE, ISSUE_FINE_MINOR),
        (MAJOR_MISSING_PIECE, ISSUE_FINE_MAJOR),
        (WHOLE_TOY_MISSING, ISSUE_FINE_MAJOR),
       # (RETIRE_VERIFIED, ISSUE_FINE_NONE),
    )


    code = models.CharField(max_length=10, blank=False)
    state = models.IntegerField(choices=TOY_STATE_CHOICES, default=AVAILABLE)
    name = models.CharField(max_length=200)
    brand = models.ForeignKey(ToyBrand, null=True,blank=True )
    last_check = models.DateField('Date last checked', blank=True, null=True)
    last_stock_take = models.DateField(blank=True, null=True)
    member_loaned = models.ForeignKey(Member, blank=True, null=True, on_delete=models.SET_NULL)
    due_date = models.DateField(blank=True, null=True)
    borrow_date = models.DateField(blank=True, null=True)

toybox/views/feedback.py
from django.shortcuts import render
from shared import *
from django.conf import settings
from django.forms import ModelForm
from django.contrib.auth.decorators import login_required

@login_required
def feedback(request):
    context = {"title":"Feedback", "contact":settings.CONTACT}

    context.update(base_data(request))

    form=FeedbackForm()
    context.update({"feedback_form":form})

    feedback_list=Feedback.objects.all()

    context.update({"feedback":feedback_list})


    if (request.method == "POST"):
        form = FeedbackForm(request.POST)

        if form.is_valid():
            feedback=Feedback.objects.create(**form.cleaned_data)

            if request.user.first_name:
                feedback.name=request.user.first_name+" "+request.user.last_name
            else:
                feedback.name=request.user.username

            feedback.save()
            form=FeedbackForm()

        context.update({"feedback_form":form})
        #TODO export to CSV?
        # https://docs.djangoproject.com/en/1.9/howto/outputting-csv/


    return render(request, 'toybox/feedback.html', context)



class FeedbackForm(forms.Form):

    page = forms.ChoiceField(choices=Feedback.PAGE_CHOICES)
    comment=forms.CharField(widget=forms.Textarea, max_length=Feedback._meta.get_field('comment').max_length)

toybox/views/home.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from toybox.views.shared import base_data


@login_required
def home(request):
    context = {"title":"Toy Library"}
    context.update(base_data(request))
    return render(request, 'toybox/home.html', context)

toybox/views/loans.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from shared import *


def loans(request, member_id):
    # If borrow button has been pushed, handle borrow of toy and reload page
    toy_code = request.GET.get('bt')
    if (toy_code):
        toy = get_object_or_404(Toy, code=toy_code)
        member = get_object_or_404(Member, pk=member_id)
        print "Loaning toy"
        toy.borrow(member,1)
        return HttpResponseRedirect(reverse('toybox:member_loan', kwargs={'member_id': member_id}) )

    context = handle_member_search(request)

    # Always need this so search box renders
    context.update(handle_toy_search(request))

    # Only need to handle these frames if member_id set
    if (member_id):
        context.update(handle_member_summary(request, member_id))
        context.update(handle_borrowed_toy_list(request, member_id))

    # Only need to handle this frame is a toy is selected
    if (request.GET.get('tc')):
        context.update(handle_toy_summary(request))

    #base page context
    context.update({"daily_balance":23.20, "login_name":"Jess Benning"})

    #print(context)

    return render(request, 'toybox/loans.html', context)

toybox/views/other.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from shared import *
# TODO break into separate files or bring borrow logic into here and rename this file?


def home(request):
    return render(request, 'toybox/home.html', {})


def returns(request, member_id=None):

    context= handle_returns(request,member_id)

    # TODO get this from authentication and transaction register
    #base page context
    context.update({"daily_balance":23.20,"login_name":"Jess Benning"})


    # TODO get this from DB
    context.update({"issue_list":
                        ({"name":"None","value":0},
                        {"name":"Broken repairable","value":1},
                        {"name":"Broken not repairable","value":2},
                        {"name":"Minor missing piece","value":3},
                        {"name":"Major missing piece","value":4},
                        {"name":"Whole toy missing","value":5})})

    # TODO get this from DB borrowed list
    context.update({"toy_list":
                    ({"ID":"BT3", "name":"Big toy 3", "due_in":32, "issue":0, "fee":0},
                     {"ID":"BT2", "name":"Big toy 2","due_in":-3, "issue":0, "fee":2.5},
                     {"ID":"BT1", "name":"Big toy 1","due_in":52, "issue":0, "fee":0.5})})

    context.update(handle_member_search(request))

    return render(request, 'toybox/returns.html', context)


def members(request, member_id=None):
    context=handle_member_details(request, member_id)
    return render(request, 'toybox/members.html', context)


def transactions(request):
     return render(request, 'toybox/transactions.html')


def reports(request):
     return render(request, 'toybox/reports.html')

toybox/templates/toybox/base.html
<!--
context inputs:
daily_balance - decimal, currency for daily balance on top bar
login_name - logged in member name

For page html use the following template tags:
 block content
 endblock content
-->

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <title>{{title}}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="/static/toybox/bootstrap-3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/toybox/bootstrap-table-1.11.0/dist/bootstrap-table.css">
    <link rel="stylesheet" href="/static/toybox/bootstrap-datepicker-1.5.0/css/bootstrap-datepicker.min.css" />

    <script src="/static/toybox/jquery-1.11.3/jquery-1.11.3.min.js"></script>
    <script src="/static/toybox/bootstrap-3.3.5/js/bootstrap.min.js"></script>
    <script src="/static/toybox/bootstrap-table-1.11.0/dist/bootstrap-table.js"></script>
    <script src="/static/toybox/bootstrap-table-1.11.0/dist/extensions/filter-control/bootstrap-table-filter-control.js"></script>
    <script src="/static/toybox/bootstrap-table-1.11.0/dist/extensions/export/bootstrap-table-export.js"></script>
    <script src="/static/toybox/bootstrap-table-1.11.0/dist/extensions/export/tableExport.js"></script>
    <script src="/static/toybox/bootstrap-table-1.11.0/dist/extensions/cookie/bootstrap-table-cookie.js"></script>
    <script src="/static/toybox/bootstrap-datepicker-1.5.0/js/bootstrap-datepicker.min.js"></script>

    <link rel="shortcut icon" href="{% static 'toybox/favicon.ico' type='image/x-icon' %}">

    <style>


        .glyphicon.glyphicon-ok, .glyphicon.glyphicon-remove, .glyphicon.glyphicon-ban-circle
        {
            font-size: 22px;
        }

        .badge-outline-default {
            color: black;
            border: 1px solid #999;
            border-color: black;
            background-color: transparent;
        }



        span.numcircle {
          background: #888888;
          border-radius: 0.8em;
          -moz-border-radius: 0.8em;
          -webkit-border-radius: 0.8em;
          color: #ffffff;
          display: inline-block;
          font-weight: bold;
          line-height: 1.6em;
          margin-right: 5px;
          text-align: center;
          width: 1.6em;
        }


    </style>

</head>

<body>


{% include "toybox/till_popup.html" %}


<script type="text/javascript">



    //used to duplicate the side menu from the top menu (top menu hidden until collapsed)
      $(document).ready(function()
      {
        $("#duplicate-menu").html($("#menu").html());

        {% if request.session.logout == True %}

                window.location.href = {%url 'logout' %};
                console.log(window.location.href);
        {%endif%}

      });


//to deal with exporting the table with select filters - stops the choices being the column header for the exported data
//also deal with combo boxes, input text boxes and...
function DoOnCellHtmlData(cell, row, col, data)
{
    var result = "";

    if (data != "")
    {
        var html = $.parseHTML(data);

        //console.log("IN: "+data);
        $.each(html, function ()
        {


           if ($(this).prop("tagName")=="SELECT")
                result+=$(this).find(":selected").text();

           else if ($(this).prop("tagName")=="BUTTON")
                result+=$(this).text();

           else if ($(this).prop("tagName")=="INPUT")
                result+=$(this).val();

           else if ($(this).prop("tagName")=="SPAN")
                result+=$(this).text();

            if (typeof $(this).html() === 'undefined')
                result += $(this).text();
            else if (typeof $(this).attr('class') === 'undefined' || $(this).hasClass('th-inner') === true)
               result += $(this).html();
        });
    }
    //console.log("OUT: "+result);
    //console.log("------------------------------------");
    return result;
}

function logout()
{

    $('#setTillModal').modal('show');
}





{%if request.session.first_login == True or till_value_error or till_comment_error %}

        $( document ).ready(function()
        {
            $(window).load(function(){
                $('#setTillModal').modal('show');

            });

        });

{%endif%}

</script>







<!-- top nav bar -->
<nav class="navbar navbar-inverse navbar-fixed-top  "  {% if sandbox == True %} style="background-color:yellow"{%endif%}>

    <div class="container-fluid">

        <div class="navbar-header" >
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>


            <a href="{% url 'toybox:home' %}"><img class="pull-left" style="max-width:60px" src="/static/toybox/MTB_logo.png" alt="MTB logo"></a>
            <a class="navbar-brand" href="{% url 'toybox:home' %}"  style="margin-left: 5px; ">Toy Library{% if development == True %} DEVELOPMENT{%endif%}{% if sandbox == True %} SANDBOX{%endif%}</a>

            <p class="navbar-text navbar-left">{{version}}</p>

            {% if daily_balance %}
                <ul class="nav navbar-nav hidden-xs ">
                    <li><a href="{% url 'toybox:transactions' %}">Daily Balance: ${{ daily_balance|floatformat:2}}</a></li>
                </ul>
            {% endif %}
        </div>

        <div id="navbar" class="navbar-collapse collapse " style="max-height: none;">
            <ul class="nav navbar-nav navbar-right">

                {% if request.user.username %}

                <li><a href="/admin">Logged in as: {{ request.user.username }} {% if request.user.first_name %}({{request.user.first_name}} {{request.user.last_name}}){%endif%} </a></li>
                {% endif %}

                {% if enable_logout_button %}
                <li>
                    <p class="navbar-btn" style="margin-right: 10px; margin-left: 10px; ">
                        <a onclick="logout();"  class="btn btn-default">Logout</a>
                    </p>
                </li>
                {%endif%}


                <!-- these are hidden until used for collapsed menu-->
                <span id="menu" class="visible-xs nav navbar-nav " style="margin-left: 0px; ">

                    <li><a href="{% url 'toybox:borrow' %}"><strong>Borrow & Payment</strong></a></li>
                    <li><a href="{% url 'toybox:returns' %}"><strong>Return</strong></a></li>
                    <li><a href="{% url 'toybox:members' %}"><strong>Members</strong></a></li>
                    <li><a href="{% url 'toybox:toys' %}"><strong>Toys</strong></a></li>
                    <li><a href="{% url 'toybox:shifts' %}"><strong>Shifts</strong></a></li>
                    <li><a href="{% url 'toybox:transactions' %}"><strong>Transactions</strong></a></li>
                    {% if request.user.is_staff %}
                    <li><a href="/admin"><strong>Admin</strong></a></li>
                    {%endif%}

                    <li><a href="{% url 'toybox:feedback' %}"><strong>Feedback</strong></a></li>


                </span>
            </ul>
        </div>
    </div>
</nav>

<div style="padding-top:70px;" class="container-fluid">
    <div class="row-fluid">



          <!-- side menu -->
        <div class="col-xs-2  nav hidden-xs ">
            <ul class="nav nav-sidebar nav-pills nav-stacked">
                <span id="duplicate-menu" class="nav nav-sidebar nav-pills nav-stacked"></span>
                <!-- menu duplicated with java script from top menu -->
            </ul>

        </div>

        <div class="col-xs-12 col-sm-10 main ">
            <div class="container-fluid">
            <!-- Page specific code -->
            {% block content %}{% endblock content %}
            <!-- Page specific code end -->
            </div>
        </div>



    </div>
</div>


</body>
</html>

toybox/templates/toybox/till_popup.html
 <div id="set_till">

  <div class="modal" id="setTillModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
      <form  action="{{ request.get_full_path }}"  method='post'>

        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h3 class="modal-title" >Set Till</h3>
                </div>

                <div class="modal-body">
                     {% csrf_token %}
                    <label for="new_value">Till Amount</label>
                    <input name="till_value" type="text" id="new_value" class="form-control" value="{{ daily_balance|floatformat:2}}" >
                    {% if till_value_error %}
                        <label class="label label-danger">{{till_value_error}}</label>
                    {%endif%}

                    <br>

                    <label for="till_adj_comment">Till adjustment justification</label>
                    <input type="text" id="till_adj_comment" class="form-control" name="till_adj_comment">
                    {% if till_comment_error %}
                        <label class="label label-danger">{{till_comment_error}}</label>
                    {%endif%}
                </div>



                <div class="modal-footer">
                    <input type="submit" name="till_set" class="btn btn-primary" value="Set">
                    <button name="till_cancel" type="submit" class="btn btn-default" >No Change</button>
                </div>

            </div>
        </div>

      </form>
    </div>

     <script type="text/javascript">

        $( document ).ready(function()
        {
            $(window).load(function()
            {
                if ("{{till_value_error}}"=="" && "{{till_comment_error}}"=="")
                    $('#setTillModal').modal('hide');
                else
                    $('#setTillModal').modal('show');
            });
        });

    </script>

</div>

toybox/templates/toybox/toy_search_select.html
<div id="toy_search_select">
<!--initial page no message or member summary-->
 {% if toy_search_results == None %}
    <!--toys==none-->
    <!--<p></p>-->

<!--Saerch returned no toys-->
  {% elif toy_search_results|length == 0 %}
    <!--toys length ==0-->
     <!--<p>No members found</p>-->

<!--search returned more than one toy-->
 {% elif toy_search_results|length > 1 %}
    <!--toys length >1-->
     <script>

         $(document).ready(function()
        {  $('#searchModal').modal(); });

     </script>



<!-- dialog box with search results -->
    <div class="modal " id="searchModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">

                    <h4 class="modal-title" >Search Results</h4>
                </div>
                <div class="modal-body" >


                    {% if toy_search_results %}
                    <form role="form" method="post">
                        {% csrf_token %}
                        <ul class="list-group">
                            {% for toy in toy_search_results %}

                            <button type="submit"  name="select_toy" value="{{toy.id}}" onclick="ok_to_leave=true;" class="list-group-item" >
                                <img class=" img-thumbnail"  style=" max-height:70px;image-orientation:from-image;"  src="{{ MEDIA_URL }}{{ toy.image.file }}">
                                {{toy.code}}, {{ toy.name }}&nbsp

                                {% if toy in new_borrow_toy_list %}
                                 <span class="label label-danger label-as-badge">
                                        Already Borrowed
                                    </span>
                                {%else%}
                                    <span class="label {% if toy.state == toy.AVAILABLE%} label-success {%elif toy.state == toy.TO_BE_REPAIRED %}label-warning {%else %} label-danger{%endif%} label-as-badge">
                                        {{toy.get_state_display}}
                                    </span>
                                {%endif%}

                            </button>

                            {% endfor %}
                         </ul>
                    </form>

                    {% endif %}

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="ok_to_leave=true;">Dismiss</button>
                </div>
            </div>
        </div>
    </div>

<!--search returned only one member, automatically load this one-->
 {% elif toy_search_results|length == 1 %}
      <script>

            //$(document).ready(function()
           // {
            //    var url = "{{ return_page }}/{{toy_search_results.0.id }}";
            //    $(location).attr('href',url);
           // });

      </script>
{% endif %}

</div>